export { default as HomeView } from './HomeView.vue'
export { default as LoginView } from './LoginView.vue'
export { default as MyPostsView } from './MyPostsView.vue'
export { default as PostFormView } from './PostFormView.vue'
export { default as RegisterView } from './RegisterView.vue'